Hello microverse
benjaMatteo96/Hello-Microverse pull request #1
Opened 2023-04-26 17:37 UTC by benjaMatteo96

This add a new html, css, ingore documents and linters.

2023-04-26 19:23 UTC, skyv26 requested changes
## Hi @benjaMatteo96,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @skyv26 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 19:23 UTC, skyv26 commented on README.md
> +> Comming soon.
- [ ] Please remove this section from your `README.md` because your project is not going to deploy and it makes your `README.md` file unprofessional. Please keep remembering to also remove this section reference from the `table` which is at the beginning of this `README` file.

2023-04-26 19:23 UTC, skyv26 commented on README.md
> +```
- [ ] Please add the relevant information about your project and I would like to suggest you always have a `user` point of view which will help you to understand how a beginner developer can start working on your project. Kindly consider the below example.
```
git clone https://github.com/benjaMatteo96/Hello-Microverse.git
cd Hello-Microverse
```

2023-04-26 19:23 UTC, skyv26 commented on README.md
> +```
- [ ] Please add the relevant information about your project and I would like to suggest you always have a `user` point of view which will help you to understand how a beginner developer can start working on your project. Kindly consider the below example

```
cd Hello-Microverse
npm i
```

2023-04-26 19:23 UTC, skyv26 commented on README.md
> +Coming soon.
- [ ] Please add the relevant information about your project and I would like to suggest you always have a `user` point of view which will help you to understand how a beginner developer can start working on your project.

2023-04-26 19:23 UTC, skyv26 commented on README.md
> +Coming soon.
- [ ] Please remove this section from your `README.md` because your project is not going to deploy and it makes your `README.md` file unprofessional. Please keep remembering to also remove this section reference from the `table` which is at the beginning of this `README` file.

2023-04-26 19:23 UTC, skyv26 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] Please remove this section from your `README.md` because it makes your `README.md` file unprofessional. Please read the below `NOTE` and keep remembering to also remove this section reference from the `table` which is at the beginning of this `README` file.

**NOTE: Except FAQ section everything is required and important. So go ahead and add relevant things.**

2023-04-26 19:23 UTC, skyv26 commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] Kindly add the MIT `LICENSE` file in your project, as I can see you have added the path but the file doesn't exist. Adding the `MIT` license will help other developers use your project, do customize and even can contribute to your project. Please visit [this](https://github.com/microverseinc/readme-template/blob/master/MIT.md) github link and get the `MIT` license. Please follow the below steps to do this quickly: 
    - Copy the `MIT` license text and create a `LICENSE` file in your root folder. (At the same place where your index.html is right now).
    - Paste the `MIT` license text and customize it by adding your name and project name.
    - You are good to go double-check the link is working before submit for review.

2023-04-26 20:35 UTC, benjaMatteo96 commented on github/workflows/linters.yml
> +          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set u
@skyv26 Hello I really appreciate the feedback !, I have a question I need to rename the folder in my local repo and then apply a commit?

2023-04-26 20:38 UTC, benjaMatteo96 commented on README.md
> +      <li> <a href="https://reactjs.org/">CSS</a></li>
@skyv26 In this case what is the correct link?

2023-04-26 20:47 UTC, benjaMatteo96 commented on README.md
> +      <li> <a href="https://reactjs.org/">CSS</a></li>
Can be this https://developer.mozilla.org/en-US/docs/Web/html?

2023-04-26 21:53 UTC, V-Blaze requested changes
## Hi @benjaMatteo96 , 

# Almost there 🟡 

![1094a3e620ebea4cd6cf2d0aceaa8f52](https://user-images.githubusercontent.com/107632780/229645999-eb4dcb1d-5a0c-4bdd-a150-2ab5cee3f40d.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing some changes from the previous reviewers, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
-  Readme looks professional✔
- Implemented changes requested by the previous reviewer💯 🥇 ✔

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 21:53 UTC, V-Blaze commented on .stylelintrc.json
> +{
- [ ] Great job implementing all the changes requested by the previous reviewer, 👍 👍 , But I think there is one issue you need to fix to move on to the next milestone: 
- [ ] Your `stlyelint linter` is failing which means that you have some errors in your CSS file, I can see you have setup your linters. You can reference this [repo too](https://github.com/microverseinc/linters-config/tree/master/html-css), you can see what the error is by running this command in your project terminal `npx stylelint "**/*.{css,scss}"`  and you can try fixing the error by ruing this cmd `npx stylelint "**/*.{css,scss}" --fix`

2023-04-26 21:53 UTC, V-Blaze commented on README.md
> +This project is <a href= "https://github.com/benjaMatteo96/Hello-Microverse/blob/hello-microverse/license">MIT</a>(./LICENSE) licensed.
- [OPTIONAL] You did great linking your license file. 👍  But currently, the formatting doesn't look right, You can improve on this your code by replacing this `This project is <a href= "https://github.com/benjaMatteo96/Hello-Microverse/blob/hello-microverse/license">MIT</a>(./LICENSE) licensed.` with this `This project is [MIT](./license) licensed`

- Screenshot of how it looks currently:
![Screenshot 2023-04-26 214807](https://user-images.githubusercontent.com/107632780/234710960-e7dc2e2d-d2f3-41fa-a44b-aaf91cd4e71b.png)

2023-04-26 22:25 UTC, benjaMatteo96 commented on .stylelintrc.json
> +{
Can I apply that correctly on my local repo and then make a commit?

2023-04-27 02:53 UTC, skyv26 commented on github/workflows/linters.yml
> +          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set u
@benjaMatteo96 yes

2023-04-27 13:41 UTC, ademibowale approved these changes
Hi @benjaMatteo96  , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good use of Github flow ✔️

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)




- [x]  _Please check the comments under the review._

## Optional suggestions

- [ ] [Optional]I would kindly suggest you to work more on your PR description with a short summary describing introduced changes in more details, also add bulletine on each summary so as to make it professional , becouse PR descriptions make you a better programmer and teammate .A good pull request is one that you understand the point of, clarifies the intentions of the code changes, summarizes the code well and identifies some of the thought process involved in writing the code. Also, a great pull request answers some questions before they are asked.


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 14:41 UTC, merged